#version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: self-apitest-frontend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: self-apitest-backend
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: self-apitest-nginx
    ports:
      - "8000:80"  # 外部訪問 http://localhost:8000
        #volumes:
        #  - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # 掛載 Nginx 設定檔
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

